---
title: "Final Project"
author: "Morgan"
date: "2023-08-13"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Open Libraries & Open included data set 
```{r code0, eval=FALSE}
library(rfm)
library(dplyr)
library(magrittr)
library(lubridate)
library(devtools)

# library(rfm) includes a sample data set rfm_data_orders
df <- rfm_data_orders 
df
```

2. RFM analysis for 12/31/2006
```{r code1, eval=FALSE}
date <- lubridate::as_date("2006-12-31") # specify the date

# use “rfm_table()” function for generating a report. Output is a table
report <- rfm_table_order(df, customer_id, order_date, revenue, date)
report
```
2.1 RFM Data Visualization - Histogram, Customers by Orders as a barplot, and Heat Map
```{r 1vis, eval=FALSE, echo=TRUE}
rfm_order_dist(report)

rfm_histograms(report)

rfm_heatmap(report)

rfm_rm_plot(report)

rfm_fm_plot(report)

rfm_rf_plot(report)

```

3. Segments: segment titles, categorize segments by RMF
```{r code2, eval=FALSE}

segment_titles <- c("First Grade", "Loyal", "Likely to be Loyal",
   "New Ones", "Could be Promising", "Require Assistance", "Getting Less Frequent",
   "Almost Out", "Can't Lose Them", "Don’t Show Up at All")

# Categorize segments by RFM numerical results
r_low <- c(4, 2, 3, 4, 3, 2, 2, 1, 1, 1)
r_high <- c(5, 5, 5, 5, 4, 3, 3, 2, 1, 2)
f_low <- c(4, 3, 1, 1, 1, 2, 1, 2, 4, 1)
f_high <- c(5, 5, 3, 1, 1, 3, 2, 5, 5, 2)
m_low <- c(4, 3, 1, 1, 1, 2, 1, 2, 4, 1)
m_high  <- c(5, 5, 3, 1, 1, 3, 2, 5, 5, 2)

# rfm_segment() to divide tibble into segments, as defined by RFM results above
divisions <- rfm_segment(report, segment_titles, r_low, r_high, f_low, f_high, m_low, m_high)

# Output: tibble by segment totals
divisions %>% count(segment) %>% arrange(desc(n)) %>% rename(Segment = segment, Count = n)
```

3.1 Data Visualization by Segments - Medians by Frequency (F), Recency (R) and Monetary (M)
```{r code3, eval=FALSE}
rfm_plot_median_frequency(divisions)

rfm_plot_median_recency(divisions)

rfm_plot_median_monetary(divisions)
```
